# Generated by Django 4.0.3 on 2022-04-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_changed_order_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder_image.png', null=True, upload_to=''),
        ),
    ]
